export const ADD_TODO_MUTATION = 'ADD_TODO_MUTATION';
export const UPDATE_TODO_MUTATION = 'UPDATE_TODO_MUTATION';
export const ARCHIVE_TODO_MUTATION = 'ARCHIVE_TODO_MUTATION';
export const UNARCHIVE_TODO_MUTATION = 'UNARCHIVE_TODO_MUTATION';
export const REMOVE_TODO_MUTATION = 'REMOVE_TODO_MUTATION';